name: music_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.2
  cloudinary_public: ^0.20.0
  animated_splash_screen: ^1.3.0
  page_transition: "^2.0.9"
  just_audio: ^0.9.30
  rxdart: ^0.27.7
  image: ^4.0.2
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  workmanager: ^0.5.1
  flutter_cache_manager: ^3.3.0
  audio_video_progress_bar: ^0.11.0
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/main_img/
    - assets/sounds/